// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsc69xHUIuA0Mpixx89mlZSCdzVGDCvew',
    appId: '1:807027612272:web:8bf313c387ed835ead32b5',
    messagingSenderId: '807027612272',
    projectId: 'nccarmy-5beab',
    authDomain: 'nccarmy-5beab.firebaseapp.com',
    databaseURL: 'https://nccarmy-5beab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nccarmy-5beab.appspot.com',
    measurementId: 'G-0T5E8F6R09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC15dQvXqYwAfLX2Y1hm7XfZ9NVERt8MQ8',
    appId: '1:807027612272:android:cefe9f069294aa90ad32b5',
    messagingSenderId: '807027612272',
    projectId: 'nccarmy-5beab',
    databaseURL: 'https://nccarmy-5beab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nccarmy-5beab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDouEokhTV9K72X6I_usPY5M8EHzqpZHtI',
    appId: '1:807027612272:ios:843c557391c72f0dad32b5',
    messagingSenderId: '807027612272',
    projectId: 'nccarmy-5beab',
    databaseURL: 'https://nccarmy-5beab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nccarmy-5beab.appspot.com',
    iosBundleId: 'com.example.ncc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDouEokhTV9K72X6I_usPY5M8EHzqpZHtI',
    appId: '1:807027612272:ios:843c557391c72f0dad32b5',
    messagingSenderId: '807027612272',
    projectId: 'nccarmy-5beab',
    databaseURL: 'https://nccarmy-5beab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nccarmy-5beab.appspot.com',
    iosBundleId: 'com.example.ncc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsc69xHUIuA0Mpixx89mlZSCdzVGDCvew',
    appId: '1:807027612272:web:05d5e848b79120fcad32b5',
    messagingSenderId: '807027612272',
    projectId: 'nccarmy-5beab',
    authDomain: 'nccarmy-5beab.firebaseapp.com',
    databaseURL: 'https://nccarmy-5beab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nccarmy-5beab.appspot.com',
    measurementId: 'G-4DWPGW6X69',
  );
}
